### PR TITLE
[lambda] converting the date transformation lambda from python to go

### PR DESCRIPTION
**Pull request by ryandeivert**
to @securityclippy 

### Changes
* Note: feel free to turn this one down if you'd like, I mostly did this for consistency (not mixing py with go).
* Converting the `osquery_date_to_elastic_lambda` function from python to go.
* Updating terraform code for lambda go resource.
* Updating the `build_lambda.sh` to build the go binary for linux and zip.

### Test
* Added tests for lambda function in `lambda_function_test.go`
* Ran: `go test ./lambda_functions/osquery_date_to_elastic_lambda` with result:

`ok  	github.com/oktasecuritylabs/sgt/lambda_functions/osquery_date_to_elastic_lambda	0.024s`

### CODE REVIEW

**Comment by securityclippy** [comment]
Love the idea @ryandeivert.  Had to unfortunately resort to python as go lambda support didn't exist when this was invented, but I really support unifying on go-only code.  Will have to pull in and deploy to double check everything (because CI isn't a thing yet, sigh).  Appreciate the work!

**Comment by ryandeivert** [comment]
hey @securityclippy PTAL again - I've update the PR with aws lambda event types and added some tests for the lambda function. I've also updated the PR description to reflect this.

**Comment by mattjane-okta** [comment]
@ryandeivert looks like this build is relying on a branch copy of the logger.  Can you change that to reference the OktaSecurityLabs repo?  [See here](https://github.com/OktaSecurityLabs/sgt/pull/24/commits/f5cdccfa1118fae35bfae52207d8c0cfffe3422b#diff-c9ca084699d47446a898a7b93375137cR11)

It also looks like `build.sh` is still referencing `lambda_function` rather than `main`.  Can we get that fixed up?  Appreciate the work!

**Comment by ryandeivert** [comment]
@securityclippy just addressed both requests and amended last commit :)

**Pull request merged**
